server:
  port: 80

spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    url: jdbc:mysql://172.16.2.198:33070/mgrgo?useUnicode=true&characterEncoding=UTF8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true
    username: allenmanager
    password: allen123
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效

logging:
  level:
    com.nb.manager: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nb.manager.sys.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl